# Generated by Django 2.1 on 2019-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_alarma_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ubicacion',
            field=models.ForeignKey(default=0, on_delete=None, to='sensor.Ubicacion'),
        ),
    ]
