# Generated by Django 2.1 on 2019-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_auto_20190511_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=None, to='sensor.Empresa'),
        ),
    ]
