# Generated by Django 2.1 on 2019-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_ubicacion_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasensor',
            name='alarma_value',
            field=models.FloatField(default=-100000),
        ),
    ]
