# Generated by Django 2.1 on 2019-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0009_auto_20190525_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarma',
            old_name='valor',
            new_name='valor_max',
        ),
        migrations.RenameField(
            model_name='datasensor',
            old_name='alarma_value',
            new_name='alarma_value_min',
        ),
        migrations.AddField(
            model_name='alarma',
            name='valor_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datasensor',
            name='alarma_value_max',
            field=models.FloatField(default=100000),
        ),
    ]
